export const LOAD_PETS_SUCCESS = "LOAD_PETS_SUCCESS"
export const CREATE_PET_SUCCESS = "CREATE_PET_SUCCESS"

export const LOAD_DIARIES_SUCCESS = "LOAD_DIARIES_SUCCESS"
export const CREATE_DIARY_SUCCESS = "CREATE_DIARY_SUCCESS"
