export const LOAD_PETS_SUCCESS = "LOAD_PETS_SUCCESS"
export const CREATE_PET_SUCCESS = "CREATE_PET_SUCCESS"
export const UPDATE_PET_SUCCESS = "UPDATE_PET_SUCCESS"
export const DELETE_PET_SUCCESS = "DELETE_PET_SUCCESS"

export const LOAD_DIARIES_SUCCESS = "LOAD_DIARIES_SUCCESS"
export const CREATE_DIARY_SUCCESS = "CREATE_DIARY_SUCCESS"
export const UPDATE_DIARY_SUCCESS = "UPDATE_DIARY_SUCCESS"

